### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by comxza** [imboy-pub/imboy-flutter#3]
在线flutter_sdk版本为3.7.12   编译此项目  ，r出现如图错误，需要怎么处理呢   
![image](https://user-images.githubusercontent.com/21981010/235920863-eb9efd87-95d8-4744-9f87-2bc2b79697d6.png)

**Comment by 907198993** [comment]
3.10编译ok

**Comment by leeyisoft** [comment]
在没有发布第一个稳定版本（1.0.0）之前，我经常把flutter和相关的依赖包，更新到最新版本；

Before the first stable version (1.0.0) was released, I often updated flutter and its associated dependencies to the latest version;
